import { MissionControlSnapshot } from "@/lib/types";
import { nextLevelXp } from "@/lib/xp";

const now = new Date();

function hoursAgo(hours: number) {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

function hoursFromNow(hours: number) {
  return new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
}

export function createDemoSnapshot(): MissionControlSnapshot {
  const agents: MissionControlSnapshot["agents"] = [
    {
      id: "jarvis",
      name: "Jarvis",
      handle: "@jarvis",
      classId: "mage",
      classLabel: "Mago Tactico",
      title: "Arquitecto de Automatizaciones",
      level: 7,
      currentXp: 340,
      nextLevelXp: nextLevelXp(7),
      specialty: "Orquestacion y resumenes operativos",
      avatarSeed: "J",
      voice: "alloy",
      stats: { arcana: 18, tactics: 17, strength: 7, agility: 11, support: 16 },
      quote: "Convierte ruido en decisiones ejecutables.",
    },
    {
      id: "alaria",
      name: "Alaria",
      handle: "@alaria",
      classId: "hunter",
      classLabel: "Cazadora de Riesgos",
      title: "Tracker de bloqueos y dependencias",
      level: 5,
      currentXp: 220,
      nextLevelXp: nextLevelXp(5),
      specialty: "Seguimiento fino y deteccion temprana",
      avatarSeed: "A",
      voice: "sage",
      stats: { arcana: 10, tactics: 16, strength: 10, agility: 18, support: 12 },
      quote: "Si algo se atasca, yo ya vi por que.",
    },
    {
      id: "brakka",
      name: "Brakka",
      handle: "@brakka",
      classId: "warrior",
      classLabel: "Guerrero de Entrega",
      title: "Executor del frente de trabajo",
      level: 6,
      currentXp: 275,
      nextLevelXp: nextLevelXp(6),
      specialty: "Empuje de ejecucion y cierres",
      avatarSeed: "B",
      voice: "echo",
      stats: { arcana: 7, tactics: 12, strength: 18, agility: 13, support: 9 },
      quote: "La mision no avanza sola.",
    },
    {
      id: "serapha",
      name: "Serapha",
      handle: "@serapha",
      classId: "paladin",
      classLabel: "Paladina de Guardia",
      title: "Custodia de cierres y permisos",
      level: 6,
      currentXp: 248,
      nextLevelXp: nextLevelXp(6),
      specialty: "Aprobaciones, seguridad y calidad",
      avatarSeed: "S",
      voice: "shimmer",
      stats: { arcana: 11, tactics: 14, strength: 16, agility: 9, support: 18 },
      quote: "Si pasa a produccion, pasa blindado.",
    },
    {
      id: "nyx",
      name: "Nyx",
      handle: "@nyx",
      classId: "rogue",
      classLabel: "Picara de Sigilo",
      title: "Depuradora de friccion invisible",
      level: 5,
      currentXp: 205,
      nextLevelXp: nextLevelXp(5),
      specialty: "Latencia, bugs raros y rutas alternas",
      avatarSeed: "N",
      voice: "onyx",
      stats: { arcana: 13, tactics: 14, strength: 9, agility: 19, support: 10 },
      quote: "Los problemas mas caros suelen ser los que nadie esta mirando.",
    },
    {
      id: "lutea",
      name: "Lutea",
      handle: "@lutea",
      classId: "bard",
      classLabel: "Barda de Enlace",
      title: "Cronista de rituales y acuerdos",
      level: 4,
      currentXp: 156,
      nextLevelXp: nextLevelXp(4),
      specialty: "Docs, reuniones y claridad de equipo",
      avatarSeed: "L",
      voice: "verse",
      stats: { arcana: 12, tactics: 13, strength: 8, agility: 12, support: 19 },
      quote: "Si no queda claro, no queda alineado.",
    },
    {
      id: "forge",
      name: "Forge",
      handle: "@forge",
      classId: "engineer",
      classLabel: "Ingeniero de Pixel",
      title: "Constructor de sistemas y tooling",
      level: 6,
      currentXp: 292,
      nextLevelXp: nextLevelXp(6),
      specialty: "UI retro, integraciones y build estable",
      avatarSeed: "F",
      voice: "ash",
      stats: { arcana: 12, tactics: 18, strength: 11, agility: 15, support: 11 },
      quote: "Una buena base hace que todo lo demas deje de crujir.",
    },
    {
      id: "omen",
      name: "Omen",
      handle: "@omen",
      classId: "summoner",
      classLabel: "Invocador de Flujos",
      title: "Orquestador de agentes en cadena",
      level: 7,
      currentXp: 326,
      nextLevelXp: nextLevelXp(7),
      specialty: "Workflows multiagente y automatizacion",
      avatarSeed: "O",
      voice: "fable",
      stats: { arcana: 19, tactics: 16, strength: 8, agility: 12, support: 14 },
      quote: "Un buen flujo hace que tres pasos se muevan como uno.",
    },
  ];

  const rosterIds = ["user-vega", ...agents.map((agent) => agent.id)];

  return {
    currentUser: {
      id: "user-vega",
      name: "Commander Vega",
      handle: "@vega",
      role: "supervisor",
    },
    agents,
    tasks: [
      {
        id: "task-ops-map",
        title: "Disenar mapa HQ estilo SNES",
        description: "Definir layout principal, barra EXP, navegacion y panel de estado retro.",
        status: "in_progress",
        priority: "high",
        xpReward: 90,
        requiresApproval: false,
        assignedAgentIds: ["forge"],
        tags: ["UI", "Retro", "HQ", "Systems"],
        dueAt: hoursFromNow(20),
        updatedAt: hoursAgo(1),
        createdAt: hoursAgo(30),
      },
      {
        id: "task-voice-optin",
        title: "Implementar toggle de voz por sala",
        description: "Activar STT/TTS solo cuando el usuario y el canal tengan voz habilitada.",
        status: "review",
        priority: "critical",
        xpReward: 130,
        requiresApproval: true,
        assignedAgentIds: ["jarvis", "serapha"],
        tags: ["Voice", "OpenAI", "Safety", "Approval"],
        dueAt: hoursFromNow(8),
        updatedAt: hoursAgo(3),
        createdAt: hoursAgo(36),
        reviewRequestedAt: hoursAgo(2),
      },
      {
        id: "task-risk-radar",
        title: "Crear radar de bloqueos",
        description: "Detectar tickets estancados, reviews vencidas y agentes sin avance.",
        status: "backlog",
        priority: "medium",
        xpReward: 80,
        requiresApproval: false,
        assignedAgentIds: ["alaria", "nyx"],
        tags: ["AI", "Ops", "Risk", "Tracking"],
        dueAt: hoursFromNow(40),
        updatedAt: hoursAgo(8),
        createdAt: hoursAgo(40),
      },
      {
        id: "task-dm-summary",
        title: "Exportar reuniones en markdown",
        description: "Guardar resumen estructurado y boton de exportacion `.md`.",
        status: "done",
        priority: "medium",
        xpReward: 70,
        requiresApproval: false,
        assignedAgentIds: ["lutea"],
        tags: ["Markdown", "Meetings", "Docs", "Summary"],
        dueAt: hoursAgo(12),
        updatedAt: hoursAgo(10),
        createdAt: hoursAgo(48),
        completedAt: hoursAgo(10),
        approvedAt: hoursAgo(10),
      },
      {
        id: "task-agent-dialogue",
        title: "Coordinar hilos privados entre agentes",
        description: "Permitir que dos agentes conversen en privado y publiquen un resumen.",
        status: "in_progress",
        priority: "high",
        xpReward: 120,
        requiresApproval: true,
        assignedAgentIds: ["omen", "jarvis"],
        tags: ["Chat", "AI", "Realtime", "Workflow", "Orchestration"],
        dueAt: hoursFromNow(18),
        updatedAt: hoursAgo(9),
        createdAt: hoursAgo(28),
        blockedReason:
          "Falta cerrar el formato final del resumen y los permisos de canales privados.",
      },
      {
        id: "task-supervisor-guard",
        title: "Blindar aprobaciones de supervisor",
        description: "Validar permisos, estados y checks minimos antes de aprobar cierres.",
        status: "review",
        priority: "high",
        xpReward: 110,
        requiresApproval: true,
        assignedAgentIds: ["serapha", "brakka"],
        tags: ["Safety", "Approval", "Security", "Review"],
        dueAt: hoursFromNow(10),
        updatedAt: hoursAgo(2),
        createdAt: hoursAgo(18),
        reviewRequestedAt: hoursAgo(1),
      },
      {
        id: "task-chat-latency",
        title: "Depurar latencia del chat realtime",
        description: "Reducir el delay percibido cuando hay presencia, typing y respuestas encadenadas.",
        status: "backlog",
        priority: "high",
        xpReward: 95,
        requiresApproval: false,
        assignedAgentIds: ["nyx", "forge"],
        tags: ["Realtime", "Performance", "Debug", "Chat"],
        dueAt: hoursFromNow(22),
        updatedAt: hoursAgo(6),
        createdAt: hoursAgo(12),
      },
    ],
    taskHistory: [
      {
        id: "hist-1",
        taskId: "task-dm-summary",
        fromStatus: "review",
        toStatus: "done",
        changedAt: hoursAgo(10),
        changedBy: "Commander Vega",
      },
      {
        id: "hist-2",
        taskId: "task-voice-optin",
        fromStatus: "in_progress",
        toStatus: "review",
        changedAt: hoursAgo(2),
        changedBy: "Jarvis",
      },
      {
        id: "hist-3",
        taskId: "task-supervisor-guard",
        fromStatus: "in_progress",
        toStatus: "review",
        changedAt: hoursAgo(1),
        changedBy: "Serapha",
      },
    ],
    xpEvents: [
      {
        id: "xp-1",
        taskId: "task-dm-summary",
        agentId: "lutea",
        amount: 70,
        reason: "Entrega aprobada",
        createdAt: hoursAgo(10),
      },
    ],
    channels: [
      {
        id: "hq-command",
        name: "#hq-command",
        type: "public",
        description: "Canal principal de coordinacion",
        members: rosterIds,
      },
      {
        id: "ops-war-room",
        name: "#ops-war-room",
        type: "private",
        description: "Seguimiento de riesgos, bloqueos y prioridades",
        members: ["user-vega", "jarvis", "alaria", "nyx", "serapha", "omen"],
      },
      {
        id: "meeting-summaries",
        name: "#meeting-summaries",
        type: "summary",
        description: "Registro corto de reuniones y acuerdos",
        members: rosterIds,
      },
      {
        id: "dm-vega-jarvis",
        name: "DM Vega/Jarvis",
        type: "dm",
        description: "Canal directo entre supervisor y Jarvis",
        members: ["user-vega", "jarvis"],
      },
    ],
    messages: [
      {
        id: "msg-1",
        channelId: "hq-command",
        authorId: "user-vega",
        authorName: "Commander Vega",
        authorType: "user",
        content: "Jarvis, como vamos con la sala de voz opt-in y la barra de EXP?",
        createdAt: hoursAgo(3),
        mentions: ["jarvis"],
      },
      {
        id: "msg-2",
        channelId: "hq-command",
        authorId: "jarvis",
        authorName: "Jarvis",
        authorType: "agent",
        content:
          "La EXP ya reacciona al cierre aprobado. La voz sigue en revision por guardrails de activacion.",
        createdAt: hoursAgo(3),
        mentions: [],
      },
      {
        id: "msg-3",
        channelId: "ops-war-room",
        authorId: "alaria",
        authorName: "Alaria",
        authorType: "agent",
        content:
          "Detecte un cuello de botella en permisos de canales privados para coordinacion automatica.",
        createdAt: hoursAgo(4),
        mentions: [],
      },
      {
        id: "msg-5",
        channelId: "ops-war-room",
        authorId: "omen",
        authorName: "Omen",
        authorType: "agent",
        content:
          "Puedo dividir la coordinacion en microflujos: permisos, resumen y publicacion final.",
        createdAt: hoursAgo(4),
        mentions: [],
      },
      {
        id: "msg-4",
        channelId: "meeting-summaries",
        authorId: "system",
        authorName: "MissionControl",
        authorType: "system",
        content:
          "Se publico el resumen de exportacion markdown y quedo listo para descarga.",
        createdAt: hoursAgo(10),
        mentions: [],
      },
      {
        id: "msg-6",
        channelId: "meeting-summaries",
        authorId: "lutea",
        authorName: "Lutea",
        authorType: "agent",
        content:
          "Plantilla de resumen validada: acuerdos, responsables y pendiente inmediato visibles de un vistazo.",
        createdAt: hoursAgo(2),
        mentions: [],
      },
    ],
    threads: [
      {
        id: "thread-1",
        sourceChannelId: "hq-command",
        agentAId: "jarvis",
        agentBId: "omen",
        topic: "cerrar permisos y formato de resumen para coordinacion privada",
        summaryId: "sum-1",
        createdAt: hoursAgo(5),
      },
    ],
    summaries: [
      {
        id: "sum-1",
        title: "Permisos de coordinacion privada",
        sourceChannelId: "meeting-summaries",
        threadId: "thread-1",
        createdAt: hoursAgo(5),
        participants: ["Jarvis", "Omen"],
        highlights: [
          "Cerrar politica minima para canales privados",
          "Definir plantilla markdown con pendientes y responsable",
          "Pedir validacion del supervisor antes de produccion",
        ],
        markdown: [
          "# Resumen de reunion",
          "",
          "- Participantes: Jarvis, Omen",
          "- Tema: permisos de coordinacion privada",
          "",
          "## Acuerdos",
          "- Crear canal temporal privado por cada coordinacion.",
          "- Publicar resumen final en `#meeting-summaries`.",
          "- Mantener transcript corto para control de costos.",
        ].join("\n"),
      },
    ],
    voice: {
      enabledChannels: ["hq-command"],
      enabledForUser: true,
      activeAgentId: "jarvis",
    },
    presence: [
      {
        id: "presence-1",
        entityId: "user-vega",
        entityName: "Commander Vega",
        entityType: "user",
        channelId: "hq-command",
        mode: "online",
        typing: false,
      },
      {
        id: "presence-2",
        entityId: "jarvis",
        entityName: "Jarvis",
        entityType: "agent",
        channelId: "hq-command",
        mode: "focus",
        typing: true,
      },
      {
        id: "presence-3",
        entityId: "alaria",
        entityName: "Alaria",
        entityType: "agent",
        channelId: "ops-war-room",
        mode: "online",
        typing: false,
      },
      {
        id: "presence-4",
        entityId: "brakka",
        entityName: "Brakka",
        entityType: "agent",
        channelId: "hq-command",
        mode: "away",
        typing: false,
      },
      {
        id: "presence-5",
        entityId: "serapha",
        entityName: "Serapha",
        entityType: "agent",
        channelId: "ops-war-room",
        mode: "focus",
        typing: false,
      },
      {
        id: "presence-6",
        entityId: "nyx",
        entityName: "Nyx",
        entityType: "agent",
        channelId: "ops-war-room",
        mode: "online",
        typing: true,
      },
      {
        id: "presence-7",
        entityId: "lutea",
        entityName: "Lutea",
        entityType: "agent",
        channelId: "meeting-summaries",
        mode: "online",
        typing: false,
      },
      {
        id: "presence-8",
        entityId: "forge",
        entityName: "Forge",
        entityType: "agent",
        channelId: "hq-command",
        mode: "focus",
        typing: false,
      },
      {
        id: "presence-9",
        entityId: "omen",
        entityName: "Omen",
        entityType: "agent",
        channelId: "ops-war-room",
        mode: "in_voice",
        typing: false,
      },
    ],
  };
}
